consumer_key = 't6GXzOVRnjV3BqGnxWEFokTtk'
consumer_secret = '4n9Nn4bmUFfcRYZOguOwpWUZZiSDPiEAvejZsxvIPB4dk9I2rO'
access_token = '4n9Nn4bmUFfcRYZOguOwpWUZZiSDPiEAvejZsxvIPB4dk9I2rO'
access_token_secret = '4n9Nn4bmUFfcRYZOguOwpWUZZiSDPiEAvejZsxvIPB4dk9I2rO'

